language: python

python:
  - "3.7"
  
# command to install dependencies
install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src/
  - pip install -r requirements.txt

# command to run tests
script:
  - python ./tests/tests.py
